Repository doganarif/GoVisual, pull requests merged in 2025-05, with the labels that each got.

#12 Feature: Add Request Comparison Tool for Side-by-Side Analysis
  internal/dashboard/handler.go
  internal/dashboard/templates/dashboard.html
  internal/dashboard/templates/layout.html
Labels: bug, enhancement

#15 Feature: Request Replay Tool for Testing and Debugging
  internal/dashboard/handler.go
  internal/dashboard/templates/components/request-details.html
  internal/dashboard/templates/dashboard.html
  internal/dashboard/templates/layout.html
Labels: enhancement

#18 Fix SQLite driver registration conflicts by supporting existing connections
  README.md
  cmd/examples/multistorage/main.go
  docs/storage-backends.md
  go.mod
  go.sum
  internal/store/factory.go
  internal/store/sqlite.go
  options.go
  wrap.go
Labels: bug

#28 Implement centralized shutdown handling for graceful application termination
  wrap.go
Labels: bug

#27 Add MongoDB support as storage back-end
  .github/workflows/test.yml
  cmd/examples/multistorage/README.md
  cmd/examples/multistorage/docker-compose.yml
  cmd/examples/multistorage/main.go
  docs/api-reference.md
  docs/configuration.md
  docs/storage-backends.md
  go.mod
  go.sum
  internal/model/request.go
  internal/store/factory.go
  internal/store/mongodb.go
  internal/store/mongodb_test.go
  options.go
Labels: enhancement
